data:
  hf_dataset_name: 'rotten_tomatoes'
  path_to_save_dataset: 'data/dataset_tokenized'
  tokenizer_model_name: 'bert-base-uncased'
  shuffle_upon_saving: True
  tokenize_padding: False
  tokenize_truncation: True
  batch_size: 32
  num_workers_train: 31
  num_workers_val: 31
  num_workers_test: 31
  shuffle_train: True
  shuffle_val: False
  shuffle_test: False


model:
  name: 'BERTForMaskedLM'
  hf_pretrained_model_name: 'bert-base-uncased'

optimizer:
  name: AdamW
  kwargs:
    lr: 2e-5
    beta1: 0.91
    beta2: 0.99
    weight_decay: 0

training:
  max_epochs: 3
  accelerator: 'auto'
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  detect_anomaly: False
