data:
  path_to_json: 'rt_scraper/results/scraped_dataset_sans_already_present_quotes.json'
  path_to_save_dataset: 'data/dataset_for_masked_lm'
  tokenizer_model_name: 'bert-base-uncased'
  tokenize_padding: False
  tokenize_truncation: False
  shuffle_upon_saving: True
  drop_unnecessary_columns: True
  single_chunk_size: 256
  mlm_probability: 0.2
  train_size: 0.93
  batch_size: 256
  num_workers_train: 10
  num_workers_val: 10
  shuffle_train: True
  shuffle_val: False