name: BaselineBERT_FrozenWeights_SimpleHead_sweep
count: 100
program: classification/training/run_experiment.py
interpreter: PYTHONPATH=. pdm run python
command:
  - ${interpreter}
  - ${program}
  - "--config_path"
  - "classification/config/models/BaselineBERT_FrozenWeights_SimpleHead.yaml"

method: random
metric:
  name: val/accuracy
  goal: maximize
parameters:
  data__batch_size:
    values: [16, 32, 64, 128]
  optimizer__name:
    values: ["Adam", "AdamW", "SGD", "RMSprop"]
  optimizer__kwargs__lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 5e-2
  optimizer__kwargs__weight_decay:
    values: [0, 1e-1, 1e-2, 1e-3, 1e-4]
  optimizer__kwargs__beta1:
    distribution: uniform
    min: 0.85
    max: 0.95
  optimizer__kwargs__beta2:
    distribution: uniform
    min: 0.95
    max: 0.999
  optimizer__kwargs__alpha:
    distribution: uniform
    min: 0.9
    max: 0.999
