program: src/training/run_experiment.py
interpreter: PYTHONPATH=. pdm run python
command:
  - ${interpreter}
  - ${program}
  - "--config_path"
  - "configs/models/BaselineBERTLogisticRegressionModel.yaml"


method: random
metric:
  name: val/accuracy
  goal: maximize
parameters:
  data__batch_size:
    values: [32, 64, 128]
  optimizer__name:
    values: ["Adam", "AdamW"]
  optimizer__kwargs__lr:
    distribution: uniform
    min: 1e-5
    max: 1e-2
  optimizer__kwargs__weight_decay:
    values: [0, 1e-2, 1e-4]