name: Augmented_and_Adapted
count: 100
program: classification/training/run_experiment.py
interpreter: PYTHONPATH=. pdm run python
command:
  - ${interpreter}
  - ${program}
  - "--config_path"
  - "configs/models/UnfrozenBERTAugmentedDomainAdaptation.yaml"

method: random
metric:
  name: val/accuracy
  goal: maximize
parameters:
  data__batch_size:
    values: [8, 16, 32, 64, 128]
  optimizer__name:
    values: ["AdamW"]
  optimizer__kwargs__lr:
    distribution: log_uniform_values
    min: 0.000002
    max: 0.001
  optimizer__kwargs__weight_decay:
    values: [0, 1e-4, 1e-5]
  optimizer__kwargs__beta1:
    distribution: uniform
    min: 0.84
    max: 0.93
  optimizer__kwargs__beta2:
    distribution: uniform
    min: 0.95
    max: 0.999
