program: training/run_experiment.py
interpreter: PYTHONPATH=. pdm run python
command:
  - ${interpreter}
  - ${program}
  - "--max_epochs"
  - "20"
  - "--model"
  - "bert_logreg_baseline"
  - ${args}
#  - "--optimizer"
#  - "Adam"

method: random
metric:
  name: val/accuracy
  goal: maximize

parameters:
    optimizer:
      values: [SGD, Adagrad, Adadelta, RMSprop, Adam, AdamW, NAdam]
#   lr:
#     distribution: uniform
#     max: 0.1
#     min: 0
#   beta0:
#     distribution: uniform
#     max: 1
#     min: 0.8
#   beta1:
#     distribution: uniform
#     max: 1
#     min: 0.8
#   weight_decay:
#     values: [0, 0.2, 0.5, 0.8, 1, 2, 3]